# Generated by Django 3.0.5 on 2020-04-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado_tarea', models.CharField(choices=[('abierta', 'abierta'), ('asignada', 'asignada'), ('en proceso', 'en proceso'), ('finalizada', 'finalizada')], max_length=20)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('empleado', models.ManyToManyField(to='appGestorProyectos.Empleado')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Tarea')),
            ],
        ),
    ]
