# Generated by Django 3.0.5 on 2020-04-17 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fecha_fin', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('nivel_prioridad', models.IntegerField(default=0)),
                ('estado_tarea', models.CharField(choices=[('', ''), ('abierta', 'abierta'), ('asignada', 'asignada'), ('en proceso', 'en proceso'), ('finalizada', 'finalizada')], default='', max_length=20)),
                ('responsable', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fecha_fin', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('presupuesto', models.IntegerField(default=0)),
                ('nombre_cliente', models.CharField(default='', max_length=20)),
                ('apellidos_cliente', models.CharField(default='', max_length=50)),
                ('email_cliente', models.EmailField(default='', max_length=100)),
                ('telefono_cliente', models.IntegerField(default=0)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Empleado')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Tarea')),
            ],
        ),
    ]
