# Generated by Django 3.0.4 on 2020-04-16 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestorProyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='apellidos_cliente',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='email_cliente',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado_tarea',
            field=models.CharField(choices=[('--------', '--------'), ('abierta', 'abierta'), ('asignada', 'asignada'), ('en proceso', 'en proceso'), ('finalizada', 'finalizada')], default='--------', max_length=20),
        ),
    ]
