# Generated by Django 3.0.4 on 2020-04-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestorProyectos', '0002_auto_20200416_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='nivel_prioridad',
            field=models.IntegerField(default=0),
        ),
    ]
